definitions:
  domain.Request:
    properties:
      code:
        type: string
      color:
        type: string
      count:
        type: integer
      name:
        type: string
      price:
        type: number
      published:
        type: boolean
    type: object
  domain.RequestUpdateNameAndPrice:
    properties:
      name:
        type: string
      price:
        type: number
    type: object
  web.Response:
    properties:
      code:
        type: string
      data: {}
      error:
        type: string
    type: object
info:
  contact:
    name: API Support
    url: adriana.meyer@mercadolivre.com
  description: This API Handle MELI Products.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: Bootcamp Go - API
  version: "1.0"
paths:
  /products/:
    get:
      consumes:
      - application/json
      description: getAll products
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "204":
          description: Não há produtos cadastrados
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server error
          schema:
            $ref: '#/definitions/web.Response'
      summary: List all products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Create a new product based on the provided JSON
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product to be saves
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/domain.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created product
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Missing fields error
          schema:
            $ref: '#/definitions/web.Response'
        "422":
          description: Json Parse error
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Save new products
      tags:
      - Products
  /products/{id}:
    delete:
      description: Delete a specific product based on ID
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No content
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: ID validation error
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Product not found
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Delete a product based on OD
      tags:
      - Products
    patch:
      consumes:
      - application/json
      description: Update a specific product based on the provided JSON
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product to be updated
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/domain.RequestUpdateNameAndPrice'
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product Updated
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: ID validation error or missing fields
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Product ID not found
          schema:
            $ref: '#/definitions/web.Response'
        "422":
          description: Json Parse error
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Update a product`s name and price based on ID
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: Update a specific product based on the provided JSON
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product to be updated
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/domain.Request'
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product Updated
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: ID validation error or missing fields
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Product ID not found
          schema:
            $ref: '#/definitions/web.Response'
        "422":
          description: Json Parse error
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Update a product based on ID
      tags:
      - Products
swagger: "2.0"
